#!/usr/bin/env node
/**
 * Emit dist/_headers (Cloudflare Pages / Netlify format) after a build.
 *
 * The CSP is generated rather than hand-written because it pins every inline
 * script by sha256. Astro emits the theme-restore and theme-toggle scripts
 * inline, so 'unsafe-inline' would otherwise be the only alternative — which on
 * a site whose whole claim is supply-chain hygiene would be an odd look.
 *
 * Stylesheets are external (Astro emits <link rel=stylesheet>), so style-src
 * needs no hashes. JSON-LD blocks are data, not executable, and browsers do not
 * apply script-src to them — verified against a real browser, not assumed.
 */
import { createHash } from 'node:crypto';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const dist = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist');

/** Every .html file under dist, as a site-absolute route. */
async function pages(dir = dist, out = []) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) await pages(full, out);
    else if (e.name.endsWith('.html')) out.push(full);
  }
  return out;
}

const routeOf = (file) => {
  const rel = path.relative(dist, file);
  if (rel === '404.html') return '/404.html';
  return '/' + rel.replace(/index\.html$/, '');
};

/** sha256 of each inline script that the browser will actually execute. */
function scriptHashes(html) {
  const hashes = new Set();
  const re = /<script([^>]*)>([\s\S]*?)<\/script>/g;
  let m;
  while ((m = re.exec(html))) {
    const [, attrs, body] = m;
    if (/\bsrc=/.test(attrs)) continue;              // external, covered by 'self'
    const type = attrs.match(/type=["']([^"']+)["']/)?.[1];
    // Non-JS types (application/ld+json) are data blocks, never executed.
    if (type && !/^(module|text\/javascript|application\/javascript)$/.test(type)) continue;
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
  return [...hashes];
}

// Applied to every route, including /rss.xml (rendered as HTML via XSLT) and any
// 404, which Cloudflare matches against the REQUEST path — so a per-page rule for
// /404.html would never fire.
const BASELINE_CSP = "default-src 'none'; style-src 'self'; img-src 'self' data:; " +
  "font-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; " +
  "object-src 'none'; upgrade-insecure-requests";

const COMMON = [
  `Content-Security-Policy: ${BASELINE_CSP}`,
  'X-Content-Type-Options: nosniff',
  'Referrer-Policy: strict-origin-when-cross-origin',
  'X-Frame-Options: DENY',
  // No feature on this site needs any of these.
  'Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=()',
  'Cross-Origin-Opener-Policy: same-origin',
  'Cross-Origin-Resource-Policy: same-origin',
  'Strict-Transport-Security: max-age=63072000; includeSubDomains; preload',
];

const csp = (hashes) => [
  "default-src 'none'",
  `script-src 'self'${hashes.length ? ' ' + hashes.join(' ') : ''}`,
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

/**
 * The CSP is only meaningful if the build cannot quietly outgrow it. Two
 * assumptions are baked into the policy, so both are enforced here rather than
 * trusted: no style attributes or <style> elements (style-src 'self' has no way
 * to allow them — hashes do not cover attributes), and no inline script beyond
 * the known theme-restore block. A build that breaks either fails loudly.
 */
const EXPECTED_INLINE_SCRIPTS = 1; // the pre-paint theme restore in Base.astro

function assertPolicyHolds(route, html, hashes) {
  const problems = [];
  if (/<[a-z]+[^>]*\sstyle=["']/i.test(html)) {
    problems.push('inline style attribute (blocked by style-src \'self\')');
  }
  if (/<style[\s>]/i.test(html)) {
    problems.push('inline <style> element (blocked by style-src \'self\')');
  }
  if (hashes.length > EXPECTED_INLINE_SCRIPTS) {
    problems.push(`${hashes.length} inline scripts, expected ${EXPECTED_INLINE_SCRIPTS} — ` +
      'an unexpected inline script would be hashed into the very policy meant to stop it');
  }
  return problems.map((p) => `${route}: ${p}`);
}

const files = await pages();
const lines = [
  '# Generated by tools/make-headers.mjs — do not edit by hand.',
  '',
  '/*',
  ...COMMON.map((h) => `  ${h}`),
  '',
  '# Immutable, content-hashed assets.',
  '/_astro/*',
  '  Cache-Control: public, max-age=31536000, immutable',
  '',
  '/og/*',
  '  Cache-Control: public, max-age=604800',
  // Share images are meant to be embedded on other origins.
  '  Cross-Origin-Resource-Policy: cross-origin',
  '',
];

const violations = [];
for (const file of files.sort()) {
  const html = await readFile(file, 'utf8');
  const hashes = scriptHashes(html);
  violations.push(...assertPolicyHolds(routeOf(file), html, hashes));
  lines.push(routeOf(file), `  Content-Security-Policy: ${csp(hashes)}`, '');
}

if (violations.length) {
  console.error('\nCSP invariant violated — refusing to write _headers:\n');
  for (const v of violations) console.error(`  ✗ ${v}`);
  console.error('\nFix the output, or change the policy deliberately.\n');
  process.exit(1);
}

await writeFile(path.join(dist, '_headers'), lines.join('\n'));
console.log(`_headers written for ${files.length} routes`);
for (const f of files.sort()) {
  console.log(`  ${routeOf(f)}  (${scriptHashes(await readFile(f, 'utf8')).length} script hashes)`);
}
